services:
  - type: web
    name: funny-friend
    env: python
    buildCommand: |
      echo "python-3.10.13" > .python-version
      pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
